[build]
builder = "nixpacks"

[deploy]
startCommand = "streamlit run app.py --server.headless true --server.enableCORS false --server.enableXsrfProtection false"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
